version: '3.9'

services:
  postgres:
    image: postgres
    init: true
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: shopping-api-service
      PGUSER: postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data

  api:
    container_name: shopping-api-service
    ports:
      - '8080:8080'
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    volumes:
      - ./app:/app
    command: ['npm', 'run', 'dev']

volumes:
  postgres:
    driver: local
