version: '3.9'

services:
  db:
    container_name: db
    image: postgres:12
    init: true
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - pgData:/var/lib/postgresql/data
    networks:
      - shopping-app

  backend:
    container_name: backend
    restart: always
    environment:
      DATABASE_URL: ${DATABASE_URL}
    links:
      - 'db:db'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - shopping-app
    volumes:
      - '.:/usr/src/app'


volumes:
  pgData: {}

networks:
  shopping-app:
    name: shopping-app
